services:
  db:
    image: postgres:16-alpine
    container_name: comunitaria-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_comuna
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s


  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: comunitaria-app
    # depends_on:
    #   db:
    #     condition: service_healthy
    restart: unless-stopped
    ports:
      - "3000:3000"     # ← Agrega esto si quieres acceder desde el navegador
    env_file:
      - .env
    environment:
      # ←←← CORREGIDO aquí
      DATABASE_URL: "postgresql://postgres:admin@db:5432/db_comuna?schema=public&connect_timeout=60"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
 postgres_data: