services:
  db:
    image: postgres:16-alpine
    container_name: comunitaria-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_comuna
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s


  api:
    build: .
    container_name: comunitaria-api
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "3000:3000"     # ← Agrega esto si quieres acceder desde el navegador
    env_file:
      - .env
    environment:
      # ←←← CORREGIDO aquí
      DATABASE_URL: "postgresql://postgres:admin@db:5432/db_comuna?schema=public&connect_timeout=60"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgadmin4:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4
  #   restart: always
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=guasimo12@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin_1204
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     db:
  #       condition: service_healthy

volumes:
  postgres_data: