services:
  db:
    image: postgres
    container_name: comunitaria-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_comuna

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=guasimo12@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin_1204
    ports:
      - "80:80"
    depends_on:
      - db
